feat: 깃허브액션 자동 배포 지우고 pr시 build 체크로 수정

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,30 +1,27 @@
-name: git push into another repo to deploy to vercel
+name: Build
 
 on:
-  push:
-    branches: [main]
+  pull_request:
+    branches:
+      - main
 
 jobs:
   build:
     runs-on: ubuntu-latest
-    container: pandoc/latex
+
     steps:
       - uses: actions/checkout@v2
-      - name: Install mustache (to update the date)
-        run: apk add ruby && gem install mustache
-      - name: creates output
-        run: sh ./build.sh
-      - name: Pushes to another repository
-        id: push_directory
-        uses: cpina/github-action-push-to-another-repository@main
-        env:
-          API_TOKEN_GITHUB: ${{ secrets.GIT_TOKEN }}
+      - name: Set up Node.js
+        uses: actions/setup-node@v2
         with:
-          source-directory: 'output'
-          destination-github-username: mimi-0506
-          destination-repository-name: mirujima_FE_deploy
-          user-email: ${{ secrets.GIT_EMAIL }}
-          commit-message: ${{ github.event.commits[0].message }}
-          target-branch: main
-      - name: Test get variable exported by push-to-another-repository
-        run: echo $DESTINATION_CLONED_DIRECTORY
+          node-version: '20'
+      - name: Install dependencies
+        run: npm install
+      - name: Run build
+        run: npm run build
+      - name: Verify build success
+        run: |
+          if [ $? -ne 0 ]; then
+            echo "Build failed!"
+            exit 1
+          fi
